name: cd

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target SDLC environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - sandbox
          - ci
          - qa
          - staging
          - preview
          - ctdev
          - cttest
          - prod

  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - develop
      - qa
      - staging
      - main

jobs:
  cd-auto:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.version.outputs.env }}
    steps:
      - id: version
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "$BRANCH_NAME"

          case "$BRANCH_NAME" in
            "main") ENV="sandbox" ;;
            "qa") ENV="qa" ;;
            *) echo "Unknown branch: $BRANCH_NAME"; exit 1 ;;
          esac
          echo "env=$ENV" >> "$GITHUB_OUTPUT"
          echo "$ENV"
        shell: bash
        
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [cd-auto]
    uses: ebsi-sagrawal/test-repo/.github/workflows/cd.yml@main
    with:
      env: ${{ needs.cd-auto.outputs.env }}
    concurrency:
      group: ${{ needs.cd-auto.outputs.env }}
      cancel-in-progress: true
