name: ci

on:
  push:
    branches:
      - features/**
      - main
      - master
      - develop
      - qa
      - staging
      - dev

jobs:
  build-and-test-ci:
    name: build and test on workflow call
    runs-on: ubuntu-latest

    steps:
      - name: Build the code
        run: |
          echo "starting code build ci"
          sleep 1m
          echo "finish code build ci"
